### ISSUE TITLE
play() not playing raw file

### ISSUE THREAD

**Issue by joel122002** [danog/magnaluna#4]
$MadelineProto->requestCall('@username')->play('test.raw')->then('test.raw'); doesn't seem to work. The call is placed but no audio is heard. Even [CallMeBot](https://www.callmebot.com/), which I assume uses the MadelineProto, has recently started having this issue.

**Comment by sahilrajput03** [comment]
Any update on this issue? I am facing same thing i.e., call is placed but my .raw files are not played!.

@joel122002 did you find solution for this?

**Comment by afeno** [comment]
All libraries based on grishka/libtgvoip are not working anymore. And nobody knows how to fix it...

**Comment by joel122002** [comment]
> Any update on this issue? I am facing same thing i.e., call is placed but my .raw files are not played!.
> 
> @joel122002 did you find solution for this?

As of today it is not fixed. I still use MadelineProto, but I needed the calling feature as notifier. In my case I was using it for notifying me when tickets for a movie are available. The raw file was just an enhancement for me and not something I needed for it to work. What I do now is place a call and send a message after the call.
